### ISSUE TITLE
issues running ros-industrial on Staubli CS8 controller

### ISSUE THREAD

**Issue by JGittles** [ros-industrial/staubli_val3_driver#47]
Hi all,

As a follow-up from my previous issue (https://github.com/ros-industrial/staubli_val3_driver/issues/46). My version issue has been sorted on srs by updating to val3 version s7.11.2 and getting the corresponding motion add-on. After verifying functionality on srs, I updated my cs8 controller to val3 s7.11.2 and installed the motion add-on. 

When I attempt to run the ros-server through my controller I run into the issue shown in the photo attached.

![Image from iOS (1)](https://user-images.githubusercontent.com/58196263/137184754-a5893d19-05c8-4cfd-9694-f0fb3b77dde7.jpg)

@enginkarlidag do you have any input on if this error is related to the ros-server/version issue? I have already contacted staubli so if they respond that this is an installation issue instead I will update here.

**Comment by enginkarlidag** [comment]
I'm sorry but I don't know about that error. Unfortunately, I also don't have access to a real robot to test it.

But if you could provide some more information, maybe I can help to find the problem. Is there any additional information in the "Events Logger"?

It seems that you are using a USB stick to load the program. Is the "ros_libs" folder also on the stick (can't see on the image)? And I assume you don't have any other version of the driver on the internal memory?

**Comment by JGittles** [comment]
ros_libs is also in the USB stick and I have deleted all of the other version in internal memory. When I pull up the events logger after a run attempt a receive the following error` 20:09 (File ros server.pjx-Line 1) Disk://ros_libs/_MsgRecvState/MsgRecvState.pjx:invalid type`

**Comment by JGittles** [comment]
update: it seems that the controller didn't like running off of a usb drive. transferring the folders to the internal disk allowed for a successful run on the arm. issue is closed.

**Comment by enginkarlidag** [comment]
I've got just an idea of how to avoid future errors when trying to load the driver from an USB drive.

I think the problem is that the VAL3 libraries are referenced from the ros_server.pjx file with a path like the following:

`Disk://ros_libs/.. `

Here, `Disk://` is referring to the standard path of user applications on the *internal memory* afaik (should be `/usr/usrapp`).

These kind of errors could be easily avoided by using relative paths which should be possible. But couldn't test that yet. Maybe someone could test that on a real controller and with a USB drive?
